global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

  tcp:
    address: :5432

certificatesResolvers:
  production:
    acme:
      email: stormk@hotmail.dk
      storage: acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /dynamic.yml
    watch: true
