version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --certificatesresolvers.cloudflare.acme.email=${EMAIL}
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    labels:
      traefik.http.routers.traefik.rule: Host(`traefik.${URL}`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true

      traefik.http.routers.traefik.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_AUTH}

      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.domains[0].main: ${URL}
      traefik.http.routers.traefik.tls.domains[0].sans: "*.${URL}"

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      traefik.http.routers.portainer.rule: Host(`portainer.${URL}`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true

      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    external: true
