version: '3'

services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    command:
      - --encryptionEnv=${PB_ENCRYPTION_KEY}
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - pocketbase_data:/pb_data
    labels:
      traefik.http.routers.pocketbase.rule: Host(`pb.${URL}`)
      traefik.http.routers.pocketbase.entrypoints: websecure
      traefik.http.routers.pocketbase.tls: true

networks:
  proxy:
    external: true

volumes:
  pocketbase_data:
    external: true
