version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - vaultwarden_data:/data
    labels:
      traefik.http.routers.vaultwarden.rule: Host(`vault.${URL}`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.tls: true
networks:
  proxy:
    external: true

volumes:
  vaultwarden_data:
    external: true
