global:
  # The smarthost and SMTP sender used for mail notifications.
  # Setup AWS SES SMTP credentials
  # smtp_smarthost: ''
  # smtp_from: 'alertmanager@domain'

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1126183334914043904/Nun7uKEHrj9g8X2mjkuLz1gTO_uWIdJAQMfoQCmYs70w2euBNmEY57fsSHrymmo6a8DE
