global:
  scrape_interval: 30s # defaults to 15s
  evaluation_interval: 30s # defaults to 15s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]

  - job_name: node_exporter
    static_configs:
      - targets: [node_exporter:9100]

  - job_name: cadvisor
    static_configs:
      - targets: [cadvisor:8080]

  - job_name: traefik
    static_configs:
      - targets: [traefik:8080]
    basic_auth:
      username: storm
      password_file: password
